name: Backend CI

on:
  push:
    branches:
      - main
    paths:
      - "backend/**"
      - .github/workflows/backend_ci.yml

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [15.2.1]
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v2
        with:
          ref: main
      - name: Deploy to backend branch
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: backend
          FOLDER: backend
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
